### ISSUE TITLE
Procedural

### ISSUE THREAD

**Issue by zhaishengfu** [magnificus/Procedural-Cities#1]
Great Tool really, thanks for sharing it!!
I have some questions.First, Is this only generated runtime??I mean, if i want to use this , i must make them fixed (So, Can I turn the whole city to static meshes?? Or If given heatmaps, Is the city generated the same each runtime??Second, I can not generate interiors , this is strange. Does it need some settings to generate interiors?? Can you give some tutorials about this software?
Thank you very much and again, Great work

**Comment by magnificus** [comment]
Thanks, yes it's all generated at runtime, you'd need to write some code to export the polygons in the way you want to turn them into static meshes, the whole project is very much a prototype, so unfortunately I haven't had time to implement things like this. But yes, generating from the same parameters with the same random seed should give the exact same result each time.

By default interiors are generated when the player pawn gets within a certain distance of buildings, in the SpawnerBP placed in the world, you can also set the world generation parameter to "Complete Generation" instead of "Aggressive Procedural Generation", which forces all buildings to generate full interiors from the beginning no matter where the player pawn is.

I might make some tutorials and also make the software easier to use in the future if I find the time, glad you like it.

**Comment by zhaishengfu** [comment]
Ok， I understand。 Indeed I tested other 2 ways to generate cities： One is Dungeon Achitect and the other is open streetmap .All your methods are different and Maybe you can see them for better ideas.Good Luck
