### ISSUE TITLE
Dependency on non-maintained 3rd party library

### ISSUE THREAD

**Issue by victorbstan** [magnificus/Procedural-Cities#2]
Hi, I see that when trying to open the project in UE4 4.18, it's asking me to install a plugin https://github.com/Koderz/RuntimeMeshComponent.

In the UE Asset Store, this plugin has not been updated since UE 4.10. 

Two questions:

1. How did you get this plugin working in your project?
2. Which UE4 engine version did you build this project with?

**Comment by RaceTheMaSe** [comment]
I cannot speak for the author but I managed to get the project running on 4.18. Therefore you have to have build the project with e.g. Visual Studio and place the the Github version of RuntimeMeshComponent into <project-folder>/Plugins. There is one line that needs modification (see [here](https://github.com/Koderz/RuntimeMeshComponent/issues/70))

**Comment by magnificus** [comment]
Hey, I've also used the same solution as RaceTheMaSe, I haven't pushed the github version of runtimemeshcomponent into the project itself because it seemed so messy and I still had some hope that the plugin would be updated (this hope is fading though).  There are two other solutions as well, you could replace everything runtimemeshcomponent-related with proceduralmeshcomponent, I've tried it and it works but for some reason it causes engine crashes for specific parameters, which is why I didn't push these changes to the repository, or you could use UE4 4.16 for which the plugin is updated.

**Comment by davedumas0** [comment]
i get this error when i try and compile the project
`\Unreal Projects\City\Intermediate\ProjectFiles\City.vcxproj" could not be found.`

**Comment by shriram17** [comment]
@Tim-Machine Did you try varying the settings under SpawnerBP Details? ( @magnificus mentioned that in another issue thread)
Changing the **Performance>Generation Mode>Complete Generation** stopped it from crashing in my case on UE4 4.18.3 (but I still get Performance Warnings in the Output Log)

**Comment by chozabu** [comment]
@victorbstan it looks like @magnificus has now included that component - this issue is solved?

@Tim-Machine I think I solved this issue ;)

@davedumas0 this may be better now - recommend deleting all files not controlled by git (including/also the .sln file, your .vs folder, and intermediate) then right click on project file and "Generate visual studio ..."

**Comment by victorbstan** [comment]
Cool, I'll have to check it out...
